### ISSUE TITLE
Failed to generate scattered structures.

### ISSUE THREAD

**Issue by ver1tatem** [PC-Logix/LanteaCraft#415] opened 2016-03-16 02:48 UTC
I've been using the newest unstable build since last issues plus a couple of mods together but Lanteacraft seems to have caused a fatal error crashing the server upon loading "[LanteaCraft]: Failed to generate scattered structures." repeats indefinitely and can't log into the game anymore. 
It started after gating to a galacticraft dimension (space station) and then jumping off and falling to the overworld. As soon as I fell into the overworld this issue began. I attempted deleting player data but this did not solve the problem. I'm hoping you can at least help pinpoint the issue for me. 
Sidenote: Can’t shut down gate once you're through and you can’t determine the gate address from any gate block only main one.

[fml-server-latest.txt](https://github.com/PC-Logix/LanteaCraft/files/175214/fml-server-latest.txt)

**Comment by CaitlynMainer** [comment] 2016-03-16 02:49
Duplicate of #414

**Closed by CaitlynMainer** 2016-03-16 02:49 UTC
