### ISSUE TITLE
Crash reports when trying to abbort dialing procces 2.0 LC-1.7.10-5

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#331] opened 2015-06-22 12:15 UTC
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 22/06/15 14:14
Description: Ticking block entity

java.lang.ExceptionInInitializerError: Address must be 7 or 9 characters long, got 0
	at lc.api.stargate.StargateAddress.<init>(StargateAddress.java:28)
	at lc.tiles.TileStargateBase.thinkServerChangeCommand(TileStargateBase.java:470)
	at lc.tiles.TileStargateBase.thinkServerTasks(TileStargateBase.java:449)
	at lc.tiles.TileStargateBase.thinkServer(TileStargateBase.java:394)
	at lc.common.base.LCTile.func_145845_h(LCTile.java:491)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at lc.api.stargate.StargateAddress.<init>(StargateAddress.java:28)
	at lc.tiles.TileStargateBase.thinkServerChangeCommand(TileStargateBase.java:470)
	at lc.tiles.TileStargateBase.thinkServerTasks(TileStargateBase.java:449)
	at lc.tiles.TileStargateBase.thinkServer(TileStargateBase.java:394)
	at lc.common.base.LCTile.func_145845_h(LCTile.java:491)

-- Block entity being ticked --
Details:
	Name: TileStargateBase // lc.tiles.TileStargateBase
	Block type: ID #168 (tile.stargateBase // lc.blocks.BlockStargateBase)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (143,63,55), Chunk: (at 15,3,7 in 8,3; contains blocks 128,0,48 to 143,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #168 (tile.stargateBase // lc.blocks.BlockStargateBase)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: Test
	All players: 1 total; [EntityPlayerMP['lieven121'/100, l='Test', x=141,23, y=64,00, z=49,79]]
	Chunk stats: ServerChunkCache: 602 Drop: 0
	Level seed: 2638855648580465792
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 2;7,59x1,3x3,2;1;village,biome_1,decoration,stronghold,mineshaft,lake,lava_lake,dungeon
	Level spawn location: World: (89,4,-96), Chunk: (at 9,0,0 in 5,-6; contains blocks 80,0,-96 to 95,255,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 53605 game time, 53605 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 28257 (now: false), thunder time: 103918 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 130260272 bytes (124 MB) / 429240320 bytes (409 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.140.1401 Minecraft Forge 10.13.3.1401 8 mods loaded, 8 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.140.1401} [Forge Mod Loader] (forge-1.7.10-10.13.3.1401-1710ls.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.3.1401} [Minecraft Forge] (forge-1.7.10-10.13.3.1401-1710ls.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	LanteaCraft-Core{1.0} [LanteaCraft Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.3.62} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.62-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ComputerCraft{1.73} [ComputerCraft] (ComputerCraft1.73.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	LanteaCraft{1.0.0-5} [LanteaCraft] (LanteaCraft-1.7.10-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['lieven121'/100, l='Test', x=141,23, y=64,00, z=49,79]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by AfterLifeLochie** [comment] 2015-06-22 22:26
Duplicate of issue #329.

Use Pastebin or some other paste service when reporting your crashes, please.

**Closed by AfterLifeLochie** 2015-06-22 22:26 UTC

**Comment by AfterLifeLochie** [comment] 2015-06-23 22:21
This is now fixed as of Build 8.
