### ISSUE TITLE
Stargates off sync

### ISSUE THREAD

**Issue by sfxworks** [PC-Logix/LanteaCraft#299] opened 2015-03-14 03:04 UTC
http://youtu.be/q8Rys7_iUYY

Running LanteaCraft-1.7.10-68.jar
On cauldron-1.7.10-1.1307.06.218

I'm in a space station with GalacticraftCore-1.7-3.0.8.257
It looks like one of your GUIs is having trouble discerning which portal to talk to? It works fine in the surface world.

The only thing I can think of to cause this would be the use of thursters in my spacestation spawn but... I've turned them off.. and they don't seem to mess with any x or y positions but rather change the skybox.

**Comment by Gunner76th** [comment] 2015-03-14 14:00
Can you recreate this issue WITHOUT using cauldron? If you can not, then the problem is with cauldron and how it is handling certain data. ALOT of issues with mods out there running on cauldron servers is caused by cauldron and not the mod.

Simple rule when submitting a bug/issue report if you use cauldron: Try to reproduce the issue in a pure Forge setup, if the issue is still present, submit it to the mod author. If you are unable to reproduce the issue on a pure Forge setup, do not post the error as it is cauldron causing the error because of how it handles the data.

**Comment by AfterLifeLochie** [comment] 2015-03-16 10:06
@Gunner76th, this has nothing at all to do with Cauldron. If it was actually a crash -- which it isn't -- then I'd still look at the issue anyway. I have worked around Cauldron issues before.

@sfxworks, do you see the same behaviour if the space-station is not moving? For reference, Stargates do not like being moved when placed as it is known to break things (Minecraft has never natively supported moving tile entities for a good reason).

**Comment by Gunner76th** [comment] 2015-03-20 21:41
@AfterLifeLochie I am very glad to see a mod author out there that is actually willing to work with/around issues caused by Cauldron. Don't get me wrong with my previous post, Cauldron is a very good and useful method of running a server, and if it wasn't for the lack of support from a lot of the major mod authors, I would be running a Cauldron server as I have seen serious server performance increases over pure forge severs. 

All that being said, I look forward to the next update, and hopefully interacting with the Tok'ra soon.

**Comment by AfterLifeLochie** [comment] 2015-04-08 08:09
Unless @sfxworks responds to this issue soon, I will have to close it.

**Comment by sfxworks** [comment] 2015-04-08 08:14
Sorry,

Haven't tried it without cauldron yet, though some funny things are happening even with the spacestation not moving...the portal is there but the multiblock structure isnt...yet the blocks to create them are...

The exact portal code is typed im for a portal in the main world with three other portals and it fails to connect. It even worked before.

Hmm...half of the multiblock structure is there (or all of it) and half of the blocks used to create the structure are there..

**Comment by AfterLifeLochie** [comment] 2015-04-08 08:20
Can you try breaking and replacing all the Stargate blocks in a non-moving station to see if it helps?

If this doesn't help, I imagine it's because Galacticraft is doing weird things when "rotating" the world, which could theoretically break Cartesian-based square-only coordinates (which we use for tracking Stargates).

**Comment by sfxworks** [comment] 2015-04-08 08:28
Thing is, galacticraft doesnr move anything. When using thrusters, it just rotates the sky box giving off the illusion of rotation

**Comment by AfterLifeLochie** [comment] 2015-04-08 08:31
In which case, there should be no reason for the issue to occur unless the Stargate is obstructed or otherwise, which doesn't make sense.

**Comment by sfxworks** [comment] 2015-04-08 08:36
...I've gotta chuck loader plugin runnin...though it shouldn't do much besides load the chunk...maybe it's threading in cauldron...don't know....

**Comment by sfxworks** [comment] 2015-04-08 08:38
And yeah, the entire chunkis loaded...though might not be at the exact same time.... Yet this happens to portAls which are within one chunk as well..

**Comment by AfterLifeLochie** [comment] 2015-04-08 08:45
I'm not sure. Can you try replicating this in a non-Cauldron environment for me, just to see if it is having some effect?

**Comment by sfxworks** [comment] 2015-04-08 08:49
...i can give you the server folder...dont really have the time to get on my console, unload the server, get a forge 1710 build, load that up, and try breaking and replacing virtual blocks at 5am...

**Comment by AfterLifeLochie** [comment] 2015-04-08 08:51
In which case, there is nothing further I can do to help diagnose the issue.

**Comment by sfxworks** [comment] 2015-04-08 08:56
Alright man, it's your mod. Just here to report a bug.

**Comment by AfterLifeLochie** [comment] 2015-04-08 09:03
Well, considering the number of bugs which are coming out of Cauldron recently, I wouldn't be surprised if it was the root cause of the issue. It could be a combination of our stuff with Cauldron, Cauldron and GC or even some other mod.

I'm not psychic; Without more information there's literally nothing I can do to fix the issue.

**Comment by sfxworks** [comment] 2015-04-08 09:04
Never called anyone one. No worries man just wait on sponge

**Closed** 2015-04-08 09:06 UTC
Labels: external mod
