### ISSUE TITLE
Traveler exits recieving gate's back side

### ISSUE THREAD

**Issue by Sarous** [PC-Logix/LanteaCraft#381] opened 2015-08-21 17:31 UTC
Title pretty well says it. Enter the dialing gate's 'front' side per normal, but you exit from the receiving gate's back side, not it's front.

LC2 1.7.10-15

**Comment by AfterLifeLochie** [comment] 2015-10-28 09:07
This is a similar problem (though not exact duplicate of) the situation described in #330.

**Comment by Cronosus** [comment] 2015-11-22 13:30
hello Lochie
 i know, you not have enought time, but can you just tell where i can fix it in code myself? (just file)

thanks

**Comment by CaitlynMainer** [comment] 2015-11-22 15:23
I'm pretty sure if lochi knew where the issue was it would have been fixed already.

**Comment by LordFokas** [comment] 2015-11-22 22:29
I'd just like to mention I've suffered from that as well and a contributor found and PR'ed a fix to me, so if you want to browse through my PRs and get your hands on that code. Even if it doesn't fix the problem it might provide some insight.

**Comment by AfterLifeLochie** [comment] 2015-11-24 22:00
I do know what the problem is - it's to do with some broken math surrounding the actual rotation of the entity facing between locations. I just haven't had the chance to sit down and debug the numbers yet.

**Comment by Cronosus** [comment] 2016-03-25 22:17
on LC2.21 still persist

**Closed** 2016-10-28 11:59 UTC
Labels: bug, duplicate, known issue, rewritten-source
