### ISSUE TITLE
Pegasus Stargate Animation is not right.

### ISSUE THREAD

**Issue by TheNoim** [PC-Logix/LanteaCraft#382] opened 2015-08-27 05:44 UTC
Hello Guys,

in the original series you can see that the ring of the pegasus stargate is nor rotating and the pegasus stargate is dialing faster then the others. I hope you can add this, because then you can build a faster alternative for faster traveling.
There you can see this: https://youtu.be/7mPbhXjTfnU

Best regards Nils

**Comment by CaitlynMainer** [comment] 2015-08-27 05:49
This is a duplicate of I know at least one issue somewhere here.  We are aware. It may be fixed eventually.  Both Lochie and I are avid fans of the show, currently the Pegasus gate is just a reskin of the Milky Way gate, same as all the rest.

**Closed by CaitlynMainer** 2015-08-27 05:49 UTC

**Comment by CaitlynMainer** [comment] 2015-08-27 05:58
I decided to go ahead and tag 'em #380 #320 #231 #267 #255 and I got bored.
