### ISSUE TITLE
crash LC2 build 13

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#364] opened 2015-07-09 22:47 UTC
http://pastebin.com/1TEvWi4W

it happend when I dissconnected/connected a gate with open peripheral 
but only if the pc booted afther the gate is Connected
its hard to explain but if you need other crash reports I can recreate it easly

**Comment by AfterLifeLochie** [comment] 2015-07-10 01:21
This is a duplicate of issue #358.

**Closed by AfterLifeLochie** 2015-07-10 01:21 UTC
Labels: bug, duplicate, rewritten-source
