### ISSUE TITLE
Pegasus gates dialing in non cannon way

### ISSUE THREAD

**Issue by hehe3301** [PC-Logix/LanteaCraft#320] opened 2015-05-13 19:24 UTC
Why does the Pegasus gate physically spin, is it possible to just have the lights spin like on the show?

**Comment by AfterLifeLochie** [comment] 2015-05-13 23:03
Duplicate of issue #231.

I love "non-canon" issues.       /s

**Closed by AfterLifeLochie** 2015-05-13 23:03 UTC
