### ISSUE TITLE
1.7.10-13 Gates aren't generating events visible to CC computers

### ISSUE THREAD

**Issue by HydrantHunter** [PC-Logix/LanteaCraft#362] opened 2015-07-09 17:22 UTC
Still not seeing events from the gates on CC computers.

Forge: 10.13.2.1291
LC: 1.7.10-13
CC: 1.74
Gopher's Peripherals: 2.2pr1

Is there any other info I can provide to help with this?

**Comment by AfterLifeLochie** [comment] 2015-07-10 00:57
I'm going to treat this issue and issue #358 as the same issue, simply because this sounds like integration with external mods is broken. I'll investigate further.

**Comment by AfterLifeLochie** [comment] 2015-07-10 01:10
Confirmed duplicate of underlying issue #358.

**Comment by HydrantHunter** [comment] 2015-07-10 02:43
Sadly, no joy with build 14 - still not seeing events.

**Comment by AfterLifeLochie** [comment] 2015-07-12 23:34
This should be fixed in commit c724120, and is in build 15; can you please check this?

**Comment by HydrantHunter** [comment] 2015-07-12 23:42
Gates are now generating visible events - thanks!

**Closed** 2015-07-12 23:46 UTC
Labels: bug, rewritten-source
