### ISSUE TITLE
Computer craft code & suggestion

### ISSUE THREAD

**Issue by ConradCreeper** [PC-Logix/LanteaCraft#310] opened 2015-04-08 19:59 UTC
I know that Computer craft is supported and I've watched a video on how to use computer craft with the mod but it does not work. can you give me a list of directions and the code needed to program the computer to dial the gate. I want to be able t fast dial.
 I also I have a couple suggestions: zFirst off can you give lantern steel some sort of durability? also can you make a block that can be put inside the gate for a catwalk. a special block so that if your using for instance lantern steel at a floor, you can put that block with covers the bottom and make it look like lantern steel so you can make it look nice. In the series the star gate is in the ground and the floor goes right through it like a covering. I thing it would be nice to add it. Also make it like a carpenters block so its compatible with any mod block.

**Comment by AfterLifeLochie** [comment] 2015-04-08 21:17
Closed, duplicate of issue #309. See my response there.

**Closed by AfterLifeLochie** 2015-04-08 21:17 UTC
