### ISSUE TITLE
LC2-16:  ComputerCraft wired modems will not attach to stargates

### ISSUE THREAD

**Issue by HydrantHunter** [PC-Logix/LanteaCraft#413] opened 2016-03-03 03:40 UTC
### Submission checklist

- [X] Check that you are running the latest recommended version of LanteaCraft.
- [X] Check that the issue isn't a known problem already (https://github.com/PC-Logix/LanteaCraft/issues).
- [ ] Check that you can repeat this issue with just LanteaCraft installed.
       NOTE: ComputerCraft is also required

### Expected behavior

ComputerCraft wired modem should attach to stargate

### Actual behavior

CC wired modem will not attach to a stargate

### Steps to reproduce

Attempt to attach a CC wired modem to a stargate (doesn't matter where on the ring you try, even the base doesn't accept a modem).

### System information

- MinecraftForge version: 10.13.4.1448 and 10.13.4.1558
- LanteaCraft version: LC2-16
- Logs: no logs

**Comment by lyqyd** [comment] 2016-03-03 17:12
As far as I'm aware, ComputerCraft's wired modems refuse to attach to blocks that return false from isOpaqueCube().  Did this work previously?

**Comment by HydrantHunter** [comment] 2016-03-03 17:17
It worked in older builds (1.7.10-70 and older), but it hasn't worked in any of the 'LC2' builds to my knowledge.

**Comment by CaitlynMainer** [comment] 2016-03-03 19:23
Don't we still ship an "Adapter" block?  I'll be honest I've not looked at LC2's codebase in quiet a while.. but even in 70 and below you had to use the Adapter that was only enabled if CC was installed.

**Comment by HydrantHunter** [comment] 2016-03-03 19:26
Lochie did some kind of magic with the LC2 builds - no CC adapter required (nor is there one available).

**Comment by AfterLifeLochie** [comment] 2016-03-04 22:21
We can't return true from `isOpaqueCube` because we aren't an opaque cube unless the Stargate is either not formed, or a Stargate block has been painted with another cover block.

The adapter was done because we had problems abstracting out the ComputerCraft API at the time, so when LC2 rolled around I took the time to fix the problem.

I suppose the easy solution is to just re-add the adapter, but perhaps there's a clever way of doing it without having to add an extra block in the game for something that _should_ theoretically be a simple task.

**Comment by lyqyd** [comment] 2016-03-04 23:48
I honestly don't see much room for a clever solution, between being unable to return true from `isOpaqueCube` under all possible circumstances, and modems refusing to attach to anything that doesn't.  It seems like any solution is going to involve a full block placed adjacent to the ring, or require that at least one block of the ring be an opaque cube.  It should be possible to *disguise* the block with something that makes sense within the universe (maybe an upscaled version of the red holding clamps visible in the SG-1 gate room?), but I can't see another way around the issue.

**Comment by AfterLifeLochie** [comment] 2016-03-05 00:35
Actually, there is a way to do this. I can just check if the caller of `isOpaqueCube` and return true if it's a ComputerCraft class invoking the method.

**Comment by AfterLifeLochie** [comment] 2016-03-15 03:34
Resolved in commit `cfdaed1c2c0dc8867a9a16fbc49f73fa77558fa9`.

Essentially the solution to the problem is to patch `isSideSolid` to pass an event to all support drivers so that `ComputerCraftPeripheralDriver` can override the return value (`computerCraft_checkIsSideSolid`) without an ASM patch.

`MethodInvocationResolver.getCallerClassNames` now returns the class-names of all active classes in the call stack, rather than the `Class<?>` instances directly.

**Closed by AfterLifeLochie** 2016-03-15 03:34 UTC
Labels: bug, question, rewritten-source
