### ISSUE TITLE
Lanteacraft 1.7.10

### ISSUE THREAD

**Issue by DezeSentinel** [PC-Logix/LanteaCraft#328] opened 2015-06-21 02:01 UTC
Hello, when will that transport Rings do they walk? I need it for my server! If you like it !!!!

**Comment by CaitlynMainer** [comment] 2015-06-21 02:02
Duplicate of #326 

As stated there, the issue tracker is not for questions, use the Thread on Minecraft Forums.

**Closed by CaitlynMainer** 2015-06-21 02:02 UTC

**Comment by DezeSentinel** [comment] 2015-06-21 02:04
How her? I do not understand your question, sorry I speak basic french!

**Comment by CaitlynMainer** [comment] 2015-06-21 02:07
Google Translate: Comme indiqué il, la question tracker est pas pour les questions, utilisez le post sur les forums Minecraft. http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292427-lanteacraft   Ils sont désactivés, vous ne pouvez pas les utiliser
